// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN9hTN--A3_DOoQWuyKuZSxemP_wvg8cA',
    appId: '1:281425863831:web:ebbaf66318b0293bd0f5d2',
    messagingSenderId: '281425863831',
    projectId: 'electronic-bookstore-app',
    authDomain: 'electronic-bookstore-app.firebaseapp.com',
    storageBucket: 'electronic-bookstore-app.firebasestorage.app',
    measurementId: 'G-2S6H6KK1CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh7_zQ2ltSsPhvUz8jEaNzq7zwQRMFIB0',
    appId: '1:281425863831:android:84d6042bb2d80a83d0f5d2',
    messagingSenderId: '281425863831',
    projectId: 'electronic-bookstore-app',
    storageBucket: 'electronic-bookstore-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZs-SLpyHLUBoI_z11hsbKC4sr4DEPEjw',
    appId: '1:281425863831:ios:348f31c0baae2bf4d0f5d2',
    messagingSenderId: '281425863831',
    projectId: 'electronic-bookstore-app',
    storageBucket: 'electronic-bookstore-app.firebasestorage.app',
    iosClientId: '281425863831-i7h40l068pjds1o4397t1fab9o12p5ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebookStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZs-SLpyHLUBoI_z11hsbKC4sr4DEPEjw',
    appId: '1:281425863831:ios:348f31c0baae2bf4d0f5d2',
    messagingSenderId: '281425863831',
    projectId: 'electronic-bookstore-app',
    storageBucket: 'electronic-bookstore-app.firebasestorage.app',
    iosClientId: '281425863831-i7h40l068pjds1o4397t1fab9o12p5ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebookStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN9hTN--A3_DOoQWuyKuZSxemP_wvg8cA',
    appId: '1:281425863831:web:44223917a1012e25d0f5d2',
    messagingSenderId: '281425863831',
    projectId: 'electronic-bookstore-app',
    authDomain: 'electronic-bookstore-app.firebaseapp.com',
    storageBucket: 'electronic-bookstore-app.firebasestorage.app',
    measurementId: 'G-5QV8ZSSPRK',
  );
}
